#' Read COLVAR from Plumed
#'
#' `read.colvar` reads a colvar file generated by Plumed and returns a colvarfile object.
#' User can specify which colums contain collective variables and bias potetnial.
#'
#' @param file COLVAR file from Plumed.
#' @param timec 1 index of the column containing time.
#' @param cvsc 2:3 numerical vector of indexes of columns containing collective variables.
#' @param biasc 4 index of the column containing the bias potential.
#' @return colvarfile object.
#'
#' @export
#' @examples
#' l1<-" 0.000000 -1.777407 2.448895 0.000000"
#' l2<-" 0.200000 -1.200988 2.527485 0.000000"
#' l3<-" 0.400000 -1.619547 2.940819 0.000000"
#' l4<-" 0.600000 -2.158700 -2.619621 0.000000"
#' l5<-" 0.800000 -2.166794 2.961958 0.000000"
#' l6<-" 1.000000 -1.408921 2.808417 0.000000"
#' l7<-" 1.200000 -2.143911 2.381913 0.018102"
#' l8<-" 1.400000 -1.970727 2.993245 0.143235"
#' l9<-" 1.600000 -2.396591 2.939432 0.004027"
#' l10<-" 1.800000 -2.262091 2.837568 0.017447"
#' snaps<-c(l1,l2,l3,l4,l5,l6,l7,l8,l9,l10)
#' tf <- tempfile()
#' writeLines(snaps, tf)
#' read.colvar(tf, timec=1, cvs=2:3, bias=4)
read.colvar<-function(file="COLVAR", cvsc=2:3, biasc=4) {
  colvarf<-read.table(file, header=F, comment.char="#")
  if(sum(ncol(colvarf)>cvs)>0) {
    stop("Error: Number of columns in COLVAR file smaller than CV indexes")
  }
  if(ncol(colvarf)>biasc) {
    stop("Error: Number of columns in COLVAR file smaller than bias index")
  }
  if(ncol(colvarf)>timec) {
    stop("Error: Number of columns in COLVAR file smaller than time index")
  }
  colvars<-list(filename=file, times=colvatf[,timec], cvs=colvarf[,cvs], bias=colvarf[,biasc])
  class(colvars) <- "colvarfilefile"
  return(colvars)
}

#' Print colvarfile
#'
#' `print.colvarfile` prints dimensionality and size of a colvarfile object.
#'
#' @param x colvarfile object.
#' @param ... further arguments passed to or from other methods.
#'
#' @export
#' @examples
#' acealanmeCVs
print.colvarfile<-function(x,...) {
  cat("collective variable record ")
  cat(x$filename)
  cat(" containing ")
  cat(ncol(x$cvs))
  cat(" collective variables and ")
  cat(nrow(x$cvs))
  cat(" records\n")
}

#' Print summary for colvarfile
#'
#' `summary.colvarfile` prints dimensionality, size and minima/maxima of
#; collective variables and bias in a colvarfile object.
#'
#' @param x colvarfile object.
#' @param ... further arguments passed to or from other methods.
#'
#' @export
#' @examples
#' summary(acealanmeCVs)
summary.colvarfile<-function(x,...) {
  cat("collective variable record ")
  cat(x$filename)
  cat(" containing ")
  cat(ncol(x$cvs))
  cat(" collective variables and ")
  cat(nrow(x$cvs))
  cat(" records\n")
  cat("Time from ")
  cat(min(x$times))
  cat(" to ")
  cat(max(x$times))
  cat("\n")
  for(i in 1:ncol(x$cvs)) {
    cat("CV")
    cat(i)
    cat(" from ")
    cat(min(x$cvs[,i]))
    cat(" to ")
    cat(max(x$cvs[,i]))
    cat("\n")
  }
  cat("Bias from ")
  cat(min(x$bias))
  cat(" to ")
  cat(max(x$bias))
  cat("\n")
}

#' Print first n lines of colvarfile
#'
#' `head.colvarfile` prints first n lines of a colvarfile object.
#'
#' @param x colvarfile object.
#' @param n number of lines (default 10).
#' @param ... further arguments passed to or from other methods.
#'
#' @export
#' @examples
#' head(acealanmeCVs)
head.colvarfile<-function(x, n=10,...) {
  colnames <- c("time")
  for(i in 1:ncol(x$cvs)) {
    colnames <- c(colnames, paste("CV", toString(i), sep=""))
  }
  colnames <- c(colnames, "bias")
  outdf <- data.frame(x$times[1:n], x$cvs[1:n,], x$bias[1:n])
  names(outdf) <- colnames
  return(outdf)
}

#' Print last n lines of colvarfile
#'
#' `tail.colvarfile` prints last n lines of a colvarfile object.
#'
#' @param x colvarfile object.
#' @param n number of lines (default 10).
#' @param ... further arguments passed to or from other methods.
#'
#' @export
#' @examples
#' tail(acealanmeCVs)
tail.colvarfile<-function(x, n=10,...) {
  colnames <- c("time")
  for(i in 1:ncol(x$cvs)) {
    colnames <- c(colnames, paste("CV", toString(i), sep=""))
  }
  colnames <- c(colnames, "bias")
  outdf <- data.frame(x$times[length(time)-n:length(time)], x$cvs[length(time)-n:length(time),], x$bias[length(time)-n:n])
  names(outdf) <- colnames
  return(outdf)
}

#' @export
`+.colvarfile`<-function(cv1, cv2) {
  cat("Warning: File name of only the firs colvar file will be retained\n")
  if(ncol(cv1$cvs)!=ncol(cv2$cvs)) {
    stop("Error: You can sum only colvar files of same dimension")
  }
  cat("Warning: Times will be concatenated, not prolonged\n")
  colvars<-list(filename=cv1$file, times=c(cv1$times, cv2$times),
                cvs=rbind(cv1$cvs,cv2$cvs), bias=c(cv1$bias,cv2$bias))
  class(colvars) <- "colvarfilefile"
  return(colvars)
}


